spring:
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

minio:
  endpoint: http://localhost:9090 #MinIO服务所在地址
  bucketName: gmall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
